workflows:
  android-check:
    name: Android Check
    instance_type: mac_mini_m2

    environment:
      flutter: 3.44.7

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Build debug APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk


  android-release:
    name: Android Release
    instance_type: mac_mini_m2

    environment:
      flutter: 3.44.7

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Build release AAB
        script: |
          flutter clean
          flutter pub get
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/*.aab
