workflows:
  android-check:
    name: مساح ومقاول - Android Check
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.44.7
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Analyze
        script: flutter analyze
      - name: Build debug APK
        script: flutter build apk --debug --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  android-release:
    name: مساح ومقاول - Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.44.7
      vars:
        PACKAGE_NAME: "com.iraqia.amr"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Analyze
        script: flutter analyze
      - name: Build Android App Bundle
        script: flutter build appbundle --release --build-number=$BUILD_NUMBER --android-skip-build-dependency-validation
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
